complexity:
  script:
  - xenon --max-average A --max-modules B --max-absolute B .
  tags:
  - docker

flake8:
  script:
  - flake8 *
  tags:
  - docker

deploy:
  image: hellobink/ansible
  stage: deploy
  environment: dev
  script:
  - cd ~/ansible && ansible-playbook playbooks/deploy/pythonproject.yml -e project=cyclops -e hosts=dev_web
  only:
  - master
  tags:
  - shell
