complexity:
  script:
    - xenon --max-average A --max-modules B --max-absolute B .

flake8:
  script:
    - flake8 *

deploy:
  image: hellobink/ansible
  stage: deploy
  environment: dev
  script:
  - cd /ansible && ansible-playbook playbooks/deploy/pythonproject.yml -e project=cyclops -e hosts=dev_web
  only:
  - master
