stages:
  - tests
  - build
  - deploy

tests:
  stage: tests
  image: binkhq/python:3.9
  script:
    - pip install pipenv
    - pipenv install --dev --system --deploy --ignore-pipfile
    - pytest cyclops/tests --cov=cyclops

complexity:
  stage: tests
  image: binkhq/python:3.9
  script:
  - pip install xenon
  - xenon --max-average A --max-modules B --max-absolute B .

flake8:
  stage: tests
  image: binkhq/python:3.9
  script:
  - pip install flake8
  - flake8

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - export CTAG="master-$(date +%F-%H%M%S)"
    - docker build --pull -t "$CI_REGISTRY/cyclops:master" -t "$CI_REGISTRY/cyclops:$CTAG" .
    - docker push "$CI_REGISTRY/cyclops:master"
    - docker push "$CI_REGISTRY/cyclops:$CTAG"
  only:
    - master
