complexity:
  script:
  - xenon --max-average A --max-modules B --max-absolute B .
  tags:
  - docker

flake8:
  script:
  - flake8 *
  tags:
  - docker

deploy:
  stage: deploy
  environment: latest
  script:
    - docker build -t hellobink/cyclops:latest .
    - docker login -u binkautomation -p epitome-generic-basilisk
    - docker push hellobink/cyclops:latest
  only:
    - master
  tags:
    - shell
