complexity:
  script:
  - xenon --max-average A --max-modules B --max-absolute B .
  tags:
  - docker

flake8:
  script:
  - flake8 *
  tags:
  - docker

deploy:
  stage: deploy
  script:
    - docker build -t registry.gitlab.com/hellobink/olympus/cyclops/image:build-$CI_PIPELINE_ID -t registry.gitlab.com/hellobink/olympus/cyclops/image:latest .
    - docker login registry.gitlab.com -u binkautomation -p $REPO_PASS
    - docker push registry.gitlab.com/hellobink/olympus/cyclops/image:latest
    - docker push registry.gitlab.com/hellobink/olympus/cyclops/image:build-$CI_PIPELINE_ID
    - docker rmi registry.gitlab.com/hellobink/olympus/cyclops/image:latest
    - docker rmi registry.gitlab.com/hellobink/olympus/cyclops/image:build-$CI_PIPELINE_ID
  only:
    - master
  tags:
    - shell

