stages:
  - tests
  - build
  - deploy

tests:
  stage: tests
  image: binkhq/python:3.8
  script:
    - pip install pipenv==2020.8.13
    - pipenv install --dev --system --deploy --ignore-pipfile
    - pytest cyclops/tests --cov=cyclops

complexity:
  stage: tests
  image: binkhq/python:3.8
  script:
  - pip install xenon
  - xenon --max-average A --max-modules B --max-absolute B .

flake8:
  stage: tests
  image: binkhq/python:3.8
  script:
  - pip install flake8
  - flake8 .

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker build --pull -t "$CI_REGISTRY/cyclops:latest" -t "$CI_REGISTRY/cyclops:master-$CI_COMMIT_SHORT_SHA" .
    - docker push "$CI_REGISTRY/cyclops:latest"
    - docker push "$CI_REGISTRY/cyclops:master-$CI_COMMIT_SHORT_SHA"
  only:
    - master
